[package]
name = "nimiq-rpc-server"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "JSON RPC server for the Nimiq Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
futures = { workspace = true }
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.49", features = ["rt"] }
tokio-stream = "0.1"

nimiq-account = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true, features = ["full"] }
nimiq-hash = { workspace = true }
nimiq-jsonrpc-core = { workspace = true }
nimiq-jsonrpc-derive = { workspace = true }
nimiq-jsonrpc-server = { workspace = true }
nimiq-keys = { workspace = true, features = ["serde-derive"] }
nimiq-primitives = { workspace = true, features = [
    "coin",
    "account",
    "serde-derive",
] }
nimiq-rpc-interface = { workspace = true }
nimiq-serde = { workspace = true }
